### Transposing Arrays and Swapping Axes

In [1]:
import numpy as np
arr = np.arange(15).reshape((3,5))

In [2]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr = np.random.randn(6,3)

In [5]:
arr

array([[ 0.44416769, -0.62993643,  0.2664657 ],
       [ 0.04281666,  0.26885629,  0.18746263],
       [ 1.75458743, -1.44741142,  0.39083526],
       [ 0.48857736, -2.09887725, -1.07921136],
       [-0.28523382,  1.5171805 , -0.89272727],
       [-0.71711263,  0.25497749,  0.01293872]])

In [6]:
np.dot(arr.T,arr)

array([[ 4.11201193, -4.44895843,  0.53021586],
       [-4.44895843,  9.33623931,  0.23084749],
       [ 0.53021586,  0.23084749,  2.22072496]])

In [7]:
# @ operator can also be used to calculate dot product
arr.T @ arr

array([[ 4.11201193, -4.44895843,  0.53021586],
       [-4.44895843,  9.33623931,  0.23084749],
       [ 0.53021586,  0.23084749,  2.22072496]])

In [8]:
# For higher dimensions transpose will accept tuple values of axis

arr = np.arange(16).reshape((2,2,4))

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [11]:
# swapaxes -- which takes a pair of axis numbers and switches the indicated axes and rearrange the data:

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### Universal Functions: Fast Element-wise Array Functions

In [13]:
arr = np.arange(10)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
x = np.random.randn(8)

In [18]:
y = np.random.randn(8)

In [19]:
x

array([-0.39018239, -0.29332386, -0.19542364,  1.88868692, -1.21776086,
        1.45295639, -0.34669048,  0.24194577])

In [20]:
y

array([-0.74982659,  0.94140293,  0.84589786,  0.02558624,  0.98757232,
        0.00499405,  2.75166724,  0.40673104])

In [21]:
np.add(x,y)

array([-1.14000897,  0.64807907,  0.65047421,  1.91427316, -0.23018853,
        1.45795044,  2.40497676,  0.64867681])

In [22]:
np.subtract(x,y)

array([ 0.3596442 , -1.23472678, -1.0413215 ,  1.86310068, -2.20533318,
        1.44796233, -3.09835772, -0.16478527])

In [23]:
np.maximum(x,y)

array([-0.39018239,  0.94140293,  0.84589786,  1.88868692,  0.98757232,
        1.45295639,  2.75166724,  0.40673104])

In [24]:
arr = np.random.randn(7)*5

In [25]:
arr

array([-7.80288215, -1.37168155, -4.0612742 , -1.05128632, -0.82057201,
        5.53363471,  3.13749797])

In [26]:
remainder,whole_part = np.modf(arr)

In [27]:
remainder

array([-0.80288215, -0.37168155, -0.0612742 , -0.05128632, -0.82057201,
        0.53363471,  0.13749797])

In [28]:
whole_part

array([-7., -1., -4., -1., -0.,  5.,  3.])

In [29]:
arr

array([-7.80288215, -1.37168155, -4.0612742 , -1.05128632, -0.82057201,
        5.53363471,  3.13749797])

In [30]:
out = np.zeros_like(arr)

In [31]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.add(arr,1)

array([-6.80288215, -0.37168155, -3.0612742 , -0.05128632,  0.17942799,
        6.53363471,  4.13749797])

In [33]:
np.add(arr,1,out=out)

array([-6.80288215, -0.37168155, -3.0612742 , -0.05128632,  0.17942799,
        6.53363471,  4.13749797])

In [34]:
out

array([-6.80288215, -0.37168155, -3.0612742 , -0.05128632,  0.17942799,
        6.53363471,  4.13749797])

In [37]:
arr = np.random.randn(8)*6
arr

array([ 4.78266566, -3.76150758, -6.47259314,  5.87566742, -1.24894202,
       -5.16501395, -9.86728333, -0.31074362])

In [38]:
np.ceil(arr)

array([ 5., -3., -6.,  6., -1., -5., -9., -0.])

In [39]:
np.floor(arr)

array([  4.,  -4.,  -7.,   5.,  -2.,  -6., -10.,  -1.])

In [40]:
np.rint(arr)

array([  5.,  -4.,  -6.,   6.,  -1.,  -5., -10.,  -0.])

In [41]:
np.modf(arr)

(array([ 0.78266566, -0.76150758, -0.47259314,  0.87566742, -0.24894202,
        -0.16501395, -0.86728333, -0.31074362]),
 array([ 4., -3., -6.,  5., -1., -5., -9., -0.]))

In [43]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False])

In [44]:
np.cos(arr)

array([ 0.07021885, -0.81392788,  0.9821159 ,  0.91810739,  0.31632619,
        0.43732768, -0.90368169,  0.95210646])

In [45]:
np.sin(arr)

array([-0.99753161,  0.58096592, -0.18827736, -0.3963317 , -0.94865048,
        0.89930223,  0.42820486, -0.30576673])

In [46]:
np.cosh(arr)

array([5.97153196e+01, 2.15182359e+01, 3.23580638e+02, 1.78132583e+02,
       1.88673014e+00, 8.75228070e+01, 9.64443314e+03, 1.04867056e+00])

In [47]:
np.sinh(arr)

array([ 5.97069460e+01, -2.14949872e+01, -3.23579093e+02,  1.78129776e+02,
       -1.59992206e+00, -8.75170940e+01, -9.64443308e+03, -3.15768809e-01])

In [48]:
np.tan(arr)

array([-14.20603754,  -0.71378059,  -0.19170584,  -0.43168338,
        -2.99896281,   2.05635788,  -0.47384479,  -0.32114763])

In [49]:
np.tanh(arr)

array([ 0.99985977, -0.99891958, -0.99999522,  0.99998424, -0.8479867 ,
       -0.99993473, -0.99999999, -0.30111345])

In [50]:
np.arccos(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_23072\3874515196.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan, 1.88677162])

In [51]:
np.logical_not(arr)

array([False, False, False, False, False, False, False, False])