In [1]:
import numpy as np

### File Input and Output Arrays

In [2]:
arr = np.arange(10)

In [3]:
np.save('some_array',arr)

In [4]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Linear Algebra

In [5]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [6]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [7]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
np.dot(x,np.ones(3))

array([ 6., 15.])