### Transposing Arrays and Swapping Axes

In [2]:
import numpy as np
arr = np.arange(15).reshape((3,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr = np.random.randn(6,3)

In [6]:
arr

array([[ 0.97686352,  0.3980003 , -0.06581173],
       [-0.59182497,  0.99645494,  0.29975235],
       [-0.84963605,  2.00007107, -0.21338335],
       [-0.9661319 ,  0.25183578,  0.90233657],
       [ 0.01183802,  0.49073058, -0.55583396],
       [ 1.53516966,  0.53444212, -0.9337644 ]])

In [7]:
np.dot(arr.T,arr)

array([[ 5.31669745, -1.31730541, -2.37223471],
       [-1.31730541,  5.74147712, -0.69885237],
       [-2.37223471, -0.69885237,  2.13479374]])

In [8]:
# @ operator can also be used to calculate dot product
arr.T @ arr

array([[ 5.31669745, -1.31730541, -2.37223471],
       [-1.31730541,  5.74147712, -0.69885237],
       [-2.37223471, -0.69885237,  2.13479374]])

In [9]:
# For higher dimensions transpose will accept tuple values of axis

arr = np.arange(16).reshape((2,2,4))

In [10]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [12]:
# swapaxes -- which takes a pair of axis numbers and switches the indicated axes and rearrange the data:

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])