### ***ndarray Object Internals***

1. **ndarray provides a way to interpret a block of homogenously typed data as a multidimensional array object**. 
2. **Part of what makes ndarray flexible is that every array object is a strided view on a block of data**.
3. **More precisely, the ndarray internally consists of the following**:
    4. *A pointer to data—that is, a block of data in RAM or in a memorymapped file*
    5. *The data type or dtype, describing fixed-size value cells in the array*
    6. *A tuple indicating the array’s shape*
    7. *A tuple of strides, integers indicating the number of bytes to “step” in order to advance one element along a dimension*

In [1]:
import numpy as np

In [2]:
np.ones((10,5)).shape

(10, 5)

In [4]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

*Strides can even negative which can allow an array to move backward in memory.*

eg. obj[[::-1]]

#### ***Numpy dtype heirarchy*** 

In [5]:
# the dtypes have superclasses np.integer and np.floating which can be used in conjunction with the np.issubdtype function
ints = np.ones(10,dtype=np.uint16)

In [6]:
floats = np.ones(10,dtype=np.float32)

In [8]:
np.issubdtype(ints.dtype,np.integer)

True

In [9]:
np.issubdtype(floats.dtype,np.floating)

True

In [10]:
# you can also see all of the parent classes of a specific dtype by calling the type's mro method:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [11]:
# we also have
np.issubdtype(ints.dtype,np.number)

True

### ***Advanced Array Manipulation***

*While much of heavy lifting for data analysis is done by pandas, you may require this at some point*

#### ***Reshaping array***

*You can convert an array from one shape to another without copying any data.*

In [12]:
arr = np.arange(8)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
# a multidimensional array can also be reshaped
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
# one of the value can be -1, in which case the value used for that dimension  will be inferred from the data
arr = np.arange(15)


In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
arr1 = np.arange(20)

In [23]:
arr1.reshape((5,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
# since an array's shape attribute is a tuple, it can be passed to reshape too:

other_arr = np.ones((3,5))

In [25]:
other_arr.shape

(3, 5)

In [26]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**The opposite operation to reshaping from one-dimensional to a higher dimension is typically known as flattening or raveling**

In [27]:
arr = np.arange(15).reshape((5,3))

In [28]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### ***C versus FORTRAN Order***