#### ***Setting Values by Broadcasting***

*The same broadcasting rule governing arithmetic operations also applies to setting values via array indexing.*

In [1]:
import numpy as np

In [2]:
arr = np.zeros((4,3))

In [3]:
arr[:] = 5

In [4]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

*if we had 1D array to set the value into the columns of an array, we can do that as long as the shape is comfortable*

In [5]:
col = np.array([1.28,-0.42,0.44,1.6])

In [6]:
arr[:] = col[:,np.newaxis]

In [7]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [8]:
arr = arr.reshape((3,4))

In [9]:
arr

array([[ 1.28,  1.28,  1.28, -0.42],
       [-0.42, -0.42,  0.44,  0.44],
       [ 0.44,  1.6 ,  1.6 ,  1.6 ]])

In [10]:
arr[:] = col[np.newaxis,:]

In [11]:
arr

array([[ 1.28, -0.42,  0.44,  1.6 ],
       [ 1.28, -0.42,  0.44,  1.6 ],
       [ 1.28, -0.42,  0.44,  1.6 ]])

In [12]:
arr[:2] = [[-1.37],[0.506]]

In [13]:
arr

array([[-1.37 , -1.37 , -1.37 , -1.37 ],
       [ 0.506,  0.506,  0.506,  0.506],
       [ 1.28 , -0.42 ,  0.44 ,  1.6  ]])

### ***Advanced Ufunc Usage***

#### ***Ufunc Instance Methods***

In [14]:
arr = np.arange(10)

In [15]:
# reduce takes the values of the array aggregates its values,optionally along an axis.
np.add.reduce(arr) 

45

In [16]:
arr.sum()

45

In [17]:
# np.logical_and to check whether the values in each row of an array are sorted:
np.random.seed(12346) # for reproducibility

In [18]:
arr = np.random.randn(5,5)

In [19]:
arr[::2].sort(1)

In [20]:
arr[:,:-1]<arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.logical_and.reduce(arr[:,:-1]<arr[:,1:],axis=1)

array([ True, False,  True, False,  True])

In [22]:
# the accumulate is related to reduce like cumsum is related to sum
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [24]:
# outer performs a cross product between two arrays
arr = np.arange(3).repeat([1,2,2])

In [25]:
arr

array([0, 1, 1, 2, 2])

In [26]:
np.multiply.outer(arr,np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [27]:
x,y = np.random.randn(3,4),np.random.randn(5)

In [28]:
result = np.subtract.outer(x,y)

In [29]:
result

array([[[-0.07129513,  1.80587986,  0.04445711, -0.77002945,
          0.37076839],
        [-0.48729668,  1.38987831, -0.37154444, -1.18603099,
         -0.04523316],
        [-0.49099936,  1.38617563, -0.37524711, -1.18973367,
         -0.04893584],
        [-0.70194533,  1.17522966, -0.58619309, -1.40067964,
         -0.25988181]],

       [[-0.5388528 ,  1.33832219, -0.42310056, -1.23758711,
         -0.09678928],
        [-0.39734742,  1.47982757, -0.28159518, -1.09608173,
          0.0447161 ],
        [-0.78758534,  1.08958965, -0.6718331 , -1.48631965,
         -0.34552182],
        [-2.05029021, -0.17311522, -1.93453796, -2.74902452,
         -1.60822669]],

       [[ 0.2637349 ,  2.14090989,  0.37948715, -0.43499941,
          0.70579842],
        [-1.3352883 ,  0.54188669, -1.21953606, -2.03402261,
         -0.89322478],
        [-1.37407525,  0.50309974, -1.25832301, -2.07280956,
         -0.93201173],
        [-0.70013722,  1.17703777, -0.58438498, -1.39887153,
         -0

In [30]:
result.shape

(3, 4, 5)

In [31]:
#reduceat performs "local reduce", in an essence an array "group by" operation in which slices of the array are agregated together.

In [32]:
arr = np.arange(10)

In [33]:
np.add.reduceat(arr,[0,5,8])

array([10, 18, 17])

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr = np.multiply.outer(np.arange(4),np.arange(5))

In [36]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [37]:
np.add.reduceat(arr,[0,2,4],axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### ***Structured and Record Arrays***

In [38]:
dtype = [('x', np.float64), ('y', np.int32)]

In [39]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)

In [40]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [41]:
sarr[0]

(1.5, 6)

In [42]:
sarr[0]['y']

6

In [43]:
sarr['x']

array([1.5       , 3.14159265])

#### ***Nested dtypes and Multidimensional Fields*** 

In [44]:
dtype = [('x', np.int64, 3), ('y', np.int32)]

In [45]:
arr = np.zeros(4,dtype=dtype)

In [46]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [47]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [48]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [49]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y',np.int32)]

In [50]:
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)

In [51]:
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [52]:
data['y']

array([5, 6])

In [53]:
data['x']['a']

array([1., 3.])

### ***MORE ABOUT SORTING***

In [54]:
arr = np.random.randn(6).round(2)

In [55]:
arr.sort()

In [56]:
arr

array([-1.47, -1.43, -0.1 , -0.  ,  0.14,  1.24])

In [57]:
arr = np.random.randn(3,5)

In [58]:
arr

array([[ 0.25360248, -0.18324574, -0.7066303 ,  0.42676074, -0.27757707],
       [-0.82828458, -2.76283358,  0.98349424,  0.43775139, -0.84956379],
       [ 0.71876344,  0.73289771,  0.50470465, -0.7892592 ,  0.5391877 ]])

In [59]:
arr[:,0].sort()

In [60]:
arr

array([[-0.82828458, -0.18324574, -0.7066303 ,  0.42676074, -0.27757707],
       [ 0.25360248, -2.76283358,  0.98349424,  0.43775139, -0.84956379],
       [ 0.71876344,  0.73289771,  0.50470465, -0.7892592 ,  0.5391877 ]])

In [61]:
# numpy.sort creates a new array
arr = np.random.randn(5)

In [62]:
arr

array([ 1.29070685,  0.86761856,  0.41133011,  0.44593599, -0.3171888 ])

In [63]:
np.sort(arr)

array([-0.3171888 ,  0.41133011,  0.44593599,  0.86761856,  1.29070685])

In [64]:
arr

array([ 1.29070685,  0.86761856,  0.41133011,  0.44593599, -0.3171888 ])

In [65]:
# sort also takes axis args
arr = np.random.randn(3,5).round(3)

In [66]:
arr

array([[-1.049,  1.346,  0.356, -0.092, -0.535],
       [-0.036, -0.259, -0.199,  0.574,  0.561],
       [ 0.21 , -0.808,  0.889,  1.192, -0.288]])

In [67]:
arr.sort(axis=1)

In [68]:
arr

array([[-1.049, -0.535, -0.092,  0.356,  1.346],
       [-0.259, -0.199, -0.036,  0.561,  0.574],
       [-0.808, -0.288,  0.21 ,  0.889,  1.192]])

***You may notice that there is no function for descending order. So what python users do is sort in asc order and then return reverse of the array***

In [69]:
arr[:,::-1]

array([[ 1.346,  0.356, -0.092, -0.535, -1.049],
       [ 0.574,  0.561, -0.036, -0.199, -0.259],
       [ 1.192,  0.889,  0.21 , -0.288, -0.808]])

#### ***Indirect Sorts: argsort and lexsort***

*For example, in a students table, the student's name has to be first sorted by last name and then by first name. This is example of indirect sort*

In [70]:
values = np.array([5,0,1,3,2])

In [71]:
indexer = values.argsort()

In [72]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [73]:
values[indexer]

array([0, 1, 2, 3, 5])

In [74]:
arr = np.random.randn(3,5).round(3)

In [75]:
arr

array([[-1.641, -1.605, -1.246, -1.023,  0.53 ],
       [ 0.774, -1.712,  0.756, -1.408, -0.881],
       [-0.19 , -1.126,  0.215,  1.057,  0.552]])

In [76]:
arr[0] = values

In [77]:
arr

array([[ 5.   ,  0.   ,  1.   ,  3.   ,  2.   ],
       [ 0.774, -1.712,  0.756, -1.408, -0.881],
       [-0.19 , -1.126,  0.215,  1.057,  0.552]])

In [78]:
arr[:,arr[0].argsort()]

array([[ 0.   ,  1.   ,  2.   ,  3.   ,  5.   ],
       [-1.712,  0.756, -0.881, -1.408,  0.774],
       [-1.126,  0.215,  0.552,  1.057, -0.19 ]])

In [79]:
# lexsort is similar but it performs an indirect lexicographically sort on multiple keys

In [80]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill','Barbara'])

In [81]:
last_name = np.array(['Jones', 'Arnold', 'Arnold','Jones', 'Walters'])

In [82]:
sorter = np.lexsort((first_name,last_name))

In [83]:
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [84]:
list(zip(last_name[sorter],first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

#### ***Alternative sort Algorithms***

*A stable sorting algorithm preserves the relative position of equal elements.*

In [85]:
values = np.array(['2:first', '2:second', '1:first','1:second','1:third'])

In [86]:
key = np.array([2,2,1,1,1])

In [87]:
indexer = key.argsort(kind = 'mergesort')

In [88]:
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [89]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

#### ***Partially Sorting Arrays***

*Numpy has fast methods numpy.partition and np.argpartition for partioning an array around the k-th smallest element*

In [90]:
np.random.seed(12345)

In [91]:
arr = np.random.randn(20)

In [92]:
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [93]:
np.partition(arr,3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [94]:
indices = np.argpartition(arr,3)

In [95]:
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [96]:
arr.take(indices)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

#### ***numpy.searchsorted: Finding elements in a sorted array***

*searchsorted is a method that performs binary search on a sorted array, returning the location in the array where the value need to be inserted*

In [97]:
arr = np.array([0,1,7,12,15])

In [98]:
arr.searchsorted(9)

3

In [99]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5], dtype=int64)

In [100]:
arr = np.array([0,0,0,1,1,1,1])

In [101]:
arr.searchsorted([0,1])

array([0, 3], dtype=int64)

In [102]:
arr.searchsorted([0, 1], side='right')

array([3, 7], dtype=int64)