#### ***Setting Values by Broadcasting***

*The same broadcasting rule governing arithmetic operations also applies to setting values via array indexing.*

In [1]:
import numpy as np

In [3]:
arr = np.zeros((4,3))

In [4]:
arr[:] = 5

In [5]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

*if we had 1D array to set the value into the columns of an array, we can do that as long as the shape is comfortable*

In [6]:
col = np.array([1.28,-0.42,0.44,1.6])

In [7]:
arr[:] = col[:,np.newaxis]

In [8]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [9]:
arr = arr.reshape((3,4))

In [10]:
arr

array([[ 1.28,  1.28,  1.28, -0.42],
       [-0.42, -0.42,  0.44,  0.44],
       [ 0.44,  1.6 ,  1.6 ,  1.6 ]])

In [11]:
arr[:] = col[np.newaxis,:]

In [12]:
arr

array([[ 1.28, -0.42,  0.44,  1.6 ],
       [ 1.28, -0.42,  0.44,  1.6 ],
       [ 1.28, -0.42,  0.44,  1.6 ]])

In [13]:
arr[:2] = [[-1.37],[0.506]]

In [14]:
arr

array([[-1.37 , -1.37 , -1.37 , -1.37 ],
       [ 0.506,  0.506,  0.506,  0.506],
       [ 1.28 , -0.42 ,  0.44 ,  1.6  ]])

### ***Advanced Ufunc Usage***

#### ***Ufunc Instance Methods***

In [15]:
arr = np.arange(10)

In [18]:
# reduce takes the values of the array aggregates its values,optionally along an axis.
np.add.reduce(arr) 

45

In [17]:
arr.sum()

45

In [20]:
# np.logical_and to check whether the values in each row of an array are sorted:
np.random.seed(12346) # for reproducibility

In [21]:
arr = np.random.randn(5,5)

In [22]:
arr[::2].sort(1)

In [23]:
arr[:,:-1]<arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
np.logical_and.reduce(arr[:,:-1]<arr[:,1:],axis=1)

array([ True, False,  True, False,  True])

In [27]:
# the accumulate is related to reduce like cumsum is related to sum
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [29]:
# outer performs a cross product between two arrays
arr = np.arange(3).repeat([1,2,2])

In [30]:
arr

array([0, 1, 1, 2, 2])

In [31]:
np.multiply.outer(arr,np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [32]:
x,y = np.random.randn(3,4),np.random.randn(5)

In [33]:
result = np.subtract.outer(x,y)

In [34]:
result

array([[[-0.07129513,  1.80587986,  0.04445711, -0.77002945,
          0.37076839],
        [-0.48729668,  1.38987831, -0.37154444, -1.18603099,
         -0.04523316],
        [-0.49099936,  1.38617563, -0.37524711, -1.18973367,
         -0.04893584],
        [-0.70194533,  1.17522966, -0.58619309, -1.40067964,
         -0.25988181]],

       [[-0.5388528 ,  1.33832219, -0.42310056, -1.23758711,
         -0.09678928],
        [-0.39734742,  1.47982757, -0.28159518, -1.09608173,
          0.0447161 ],
        [-0.78758534,  1.08958965, -0.6718331 , -1.48631965,
         -0.34552182],
        [-2.05029021, -0.17311522, -1.93453796, -2.74902452,
         -1.60822669]],

       [[ 0.2637349 ,  2.14090989,  0.37948715, -0.43499941,
          0.70579842],
        [-1.3352883 ,  0.54188669, -1.21953606, -2.03402261,
         -0.89322478],
        [-1.37407525,  0.50309974, -1.25832301, -2.07280956,
         -0.93201173],
        [-0.70013722,  1.17703777, -0.58438498, -1.39887153,
         -0

In [35]:
result.shape

(3, 4, 5)

In [36]:
#reduceat performs "local reduce", in an essence an array "group by" operation in which slices of the array are agregated together.

In [37]:
arr = np.arange(10)

In [38]:
np.add.reduceat(arr,[0,5,8])

array([10, 18, 17])

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.multiply.outer(np.arange(4),np.arange(5))

In [41]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [42]:
np.add.reduceat(arr,[0,2,4],axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### ***Structured and Record Arrays***

In [43]:
dtype = [('x', np.float64), ('y', np.int32)]

In [45]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)

In [46]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [47]:
sarr[0]

(1.5, 6)

In [48]:
sarr[0]['y']

6

In [49]:
sarr['x']

array([1.5       , 3.14159265])

#### ***Nested dtypes and Multidimensional Fields*** 

In [50]:
dtype = [('x', np.int64, 3), ('y', np.int32)]

In [51]:
arr = np.zeros(4,dtype=dtype)

In [52]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [53]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [54]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [55]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y',np.int32)]